- name: playbook thats installs a gihub runner and a nextjs server
  hosts: digitalocean
  vars_files:
    - vars/vars.yml
    - vars/secrets.yml
  tasks:
    - name: gets self hosted runner deployment token
      ansible.builtin.include_tasks: tasks/0_getting_runner_token.yml

    - name: creates required user and directories
      ansible.builtin.include_tasks: tasks/1_runner-user-dir.yml

    - name: installs and configures the github runner
      ansible.builtin.include_tasks: tasks/2_install-conf-runner.yml

    - name: installs nextJS
      ansible.builtin.include_tasks: tasks/3_install-nextjs.yml

    - name: ufw
      ansible.builtin.include_tasks: tasks/4_ufw.yml

