- name: Get GitHub runner registration token
  ansible.builtin.uri:
    url: "https://api.github.com/repos/dirakkk/vitrine-next/actions/runners/registration-token"
    method: POST
    headers:
      Accept: "application/vnd.github+json"
      Authorization: "Bearer {{ github_token }}"
      X-GitHub-Api-Version: "2022-11-28"
    status_code: [200, 201]
  register: github_response

- name: Extract runner token
  ansible.builtin.set_fact:
    runner_token: "{{ github_response.json.token }}"

- name: Print GitHub runner registration token
  ansible.builtin.debug:
    msg: "The GitHub runner registration token is: {{ runner_token }}"