- name: Install Node.js and npm
  apt:
    name: 
      - nodejs
      - npm
    state: present
    update_cache: yes

- name: Install pm2 globally
  npm:
    name: pm2
    global: yes
    state: present

- name: Install Next.js globally
  npm:
    name: next
    global: yes
    state: present

- name: Create Next.js project directory
  ansible.builtin.file:
    path: "{{ project_vitrine_path }}"
    state: directory
    mode: "0700"
    owner: "{{ runner_user }}"
    group: "{{ runner_group }}"